export { DocumentHead } from './DocumentHead'
export { default as Footer } from './Footer'
export { default as LanguageSwitcher } from './LanguageSwitcher'
export { default as Layout } from './Layout'
export { default as Navbar } from './Navbar'
export { OptimizedImage } from './OptimizedImage'
export { OptimizedLogo } from './OptimizedLogo'
export { ScrollToTop } from './ScrollToTop'
export { SmartRoutePreloader } from './RoutePreloader'
